using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Windows;
using System.Windows.Controls;
using Reloaded.WPF.MVVM;

namespace Reloaded.WPF.Theme.Default.AttachedProperties
{
    /// <summary>
    /// The <see cref="FixDataGridAutoGeneratingColumnStyle"/> is a simple dependency property that when
    /// applied to a DataGridView, ensures that the cells follow the actual theme style when the columns
    /// are autogenerated as opposed to the standard WPF style.
    /// </summary>
    public class FixDataGridAutoGeneratingColumnStyle : AttachedPropertyBase<FixDataGridAutoGeneratingColumnStyle, bool>
    {
        private const string TextBoxStyle = "DataGridTextStyle";
        private const string CheckBoxStyle = "DataGridCheckBoxStyle";
        private const string ComboBoxStyle = "DataGridComboBoxStyle";

        /// <inheritdoc />
        public override void OnValueChanged(DependencyObject sender, DependencyPropertyChangedEventArgs e)
        {
            bool newValue = GetValue(sender);

            if (sender is DataGrid grid)
            {
                if (newValue == false)
                {
                    grid.Columns.CollectionChanged -= ColumnsOnCollectionChanged;
                }
                else
                {
                    grid.Columns.CollectionChanged += ColumnsOnCollectionChanged;
                }
            }
        }

        private void ColumnsOnCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            foreach (var column in (ObservableCollection<DataGridColumn>) sender)
            {
                switch (column)
                {
                    case DataGridCheckBoxColumn checkboxColumn:
                    {
                        if (TryGetResource(CheckBoxStyle, out var newStyle))
                        {
                            checkboxColumn.ElementStyle = (Style)newStyle;
                            checkboxColumn.EditingElementStyle = (Style)newStyle;
                        }

                        break;
                    }
                    case DataGridTextColumn textColumn:
                    {
                        if (TryGetResource(TextBoxStyle, out var editStyle))
                            textColumn.EditingElementStyle = (Style)editStyle;

                        if (TryGetResource(typeof(TextBlock), out var elementStyle))
                            textColumn.ElementStyle = (Style)elementStyle;

                        break;
                    }
                    case DataGridComboBoxColumn comboBoxColumn:
                    {
                        if (TryGetResource(ComboBoxStyle, out var editStyle))
                            comboBoxColumn.EditingElementStyle = (Style)editStyle;

                        break;
                    }
                }
            }
        }

        private bool TryGetResource(object resourceKey, out Style newStyle)
        {
            newStyle = Application.Current.TryFindResource(resourceKey) as Style;
            if (newStyle != null)
                return true;

            return false;
        }
    }
}
